set_property PACKAGE_PIN U18 [get_ports CLK]
set_property PACKAGE_PIN F17 [get_ports RX]
set_property PACKAGE_PIN F16 [get_ports TX]
set_property IOSTANDARD LVCMOS33 [get_ports CLK]
set_property IOSTANDARD LVCMOS33 [get_ports RX]
set_property IOSTANDARD LVCMOS33 [get_ports TX]
