set_property PACKAGE_PIN F17 [get_ports RX]
set_property PACKAGE_PIN F16 [get_ports TX]
set_property PACKAGE_PIN U18 [get_ports CLK]
set_property PACKAGE_PIN N15 [get_ports RST]
set_property IOSTANDARD LVCMOS33 [get_ports CLK]
set_property IOSTANDARD LVCMOS33 [get_ports RST]
set_property IOSTANDARD LVCMOS33 [get_ports RX]
set_property IOSTANDARD LVCMOS33 [get_ports TX]

set_property PACKAGE_PIN N15 [get_ports KEY1]
set_property PACKAGE_PIN N16 [get_ports KEY2]
set_property PACKAGE_PIN T17 [get_ports KEY3]
set_property PACKAGE_PIN R17 [get_ports KEY4]
set_property IOSTANDARD LVCMOS33 [get_ports KEY1]
set_property IOSTANDARD LVCMOS33 [get_ports KEY2]
set_property IOSTANDARD LVCMOS33 [get_ports KEY3]
set_property IOSTANDARD LVCMOS33 [get_ports KEY4]
